//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class CartesianEulerPoseMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/CartesianEulerPose";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public CartesianQuantityMsg pose;

        public CartesianEulerPoseMsg()
        {
            this.header = new HeaderMsg();
            this.pose = new CartesianQuantityMsg();
        }

        public CartesianEulerPoseMsg(HeaderMsg header, CartesianQuantityMsg pose)
        {
            this.header = header;
            this.pose = pose;
        }

        public static CartesianEulerPoseMsg Deserialize(MessageDeserializer deserializer) => new CartesianEulerPoseMsg(deserializer);

        private CartesianEulerPoseMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.pose = CartesianQuantityMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "CartesianEulerPoseMsg: " +
            "\nheader: " + header.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
