//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class CartesianWrenchMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/CartesianWrench";
        public override string RosMessageName => k_RosMessageName;

        //  Cartesian Wrench
        public HeaderMsg header;
        public Geometry.WrenchMsg wrench;
        public Geometry.WrenchMsg inaccuracy;

        public CartesianWrenchMsg()
        {
            this.header = new HeaderMsg();
            this.wrench = new Geometry.WrenchMsg();
            this.inaccuracy = new Geometry.WrenchMsg();
        }

        public CartesianWrenchMsg(HeaderMsg header, Geometry.WrenchMsg wrench, Geometry.WrenchMsg inaccuracy)
        {
            this.header = header;
            this.wrench = wrench;
            this.inaccuracy = inaccuracy;
        }

        public static CartesianWrenchMsg Deserialize(MessageDeserializer deserializer) => new CartesianWrenchMsg(deserializer);

        private CartesianWrenchMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.wrench = Geometry.WrenchMsg.Deserialize(deserializer);
            this.inaccuracy = Geometry.WrenchMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.wrench);
            serializer.Write(this.inaccuracy);
        }

        public override string ToString()
        {
            return "CartesianWrenchMsg: " +
            "\nheader: " + header.ToString() +
            "\nwrench: " + wrench.ToString() +
            "\ninaccuracy: " + inaccuracy.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
