//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class ControlModeMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/ControlMode";
        public override string RosMessageName => k_RosMessageName;

        public const int POSITION_CONTROL = 0;
        public const int JOINT_IMPEDANCE = 1;
        public const int CARTESIAN_IMPEDANCE = 2;
        public const int DESIRED_FORCE = 3;
        public const int SINE_PATTERN = 4;

        public ControlModeMsg()
        {
        }
        public static ControlModeMsg Deserialize(MessageDeserializer deserializer) => new ControlModeMsg(deserializer);

        private ControlModeMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ControlModeMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
