//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class DOFMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/DOF";
        public override string RosMessageName => k_RosMessageName;

        public const int X = 1;
        public const int Y = 2;
        public const int Z = 3;
        public const int A = 4;
        public const int B = 5;
        public const int C = 6;
        public const int ROT = 7;
        public const int TRANSL = 8;
        public const int ALL = 9;

        public DOFMsg()
        {
        }
        public static DOFMsg Deserialize(MessageDeserializer deserializer) => new DOFMsg(deserializer);

        private DOFMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "DOFMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
