//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class JointStiffnessMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/JointStiffness";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public JointQuantityMsg stiffness;

        public JointStiffnessMsg()
        {
            this.header = new HeaderMsg();
            this.stiffness = new JointQuantityMsg();
        }

        public JointStiffnessMsg(HeaderMsg header, JointQuantityMsg stiffness)
        {
            this.header = header;
            this.stiffness = stiffness;
        }

        public static JointStiffnessMsg Deserialize(MessageDeserializer deserializer) => new JointStiffnessMsg(deserializer);

        private JointStiffnessMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.stiffness = JointQuantityMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.stiffness);
        }

        public override string ToString()
        {
            return "JointStiffnessMsg: " +
            "\nheader: " + header.ToString() +
            "\nstiffness: " + stiffness.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
