//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class JointQuantityMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/JointQuantity";
        public override string RosMessageName => k_RosMessageName;

        public float a1;
        public float a2;
        public float a3;
        public float a4;
        public float a5;
        public float a6;
        public float a7;

        public JointQuantityMsg()
        {
            this.a1 = 0.0f;
            this.a2 = 0.0f;
            this.a3 = 0.0f;
            this.a4 = 0.0f;
            this.a5 = 0.0f;
            this.a6 = 0.0f;
            this.a7 = 0.0f;
        }

        public JointQuantityMsg(float a1, float a2, float a3, float a4, float a5, float a6, float a7)
        {
            this.a1 = a1;
            this.a2 = a2;
            this.a3 = a3;
            this.a4 = a4;
            this.a5 = a5;
            this.a6 = a6;
            this.a7 = a7;
        }

        public static JointQuantityMsg Deserialize(MessageDeserializer deserializer) => new JointQuantityMsg(deserializer);

        private JointQuantityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.a1);
            deserializer.Read(out this.a2);
            deserializer.Read(out this.a3);
            deserializer.Read(out this.a4);
            deserializer.Read(out this.a5);
            deserializer.Read(out this.a6);
            deserializer.Read(out this.a7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.a1);
            serializer.Write(this.a2);
            serializer.Write(this.a3);
            serializer.Write(this.a4);
            serializer.Write(this.a5);
            serializer.Write(this.a6);
            serializer.Write(this.a7);
        }

        public override string ToString()
        {
            return "JointQuantityMsg: " +
            "\na1: " + a1.ToString() +
            "\na2: " + a2.ToString() +
            "\na3: " + a3.ToString() +
            "\na4: " + a4.ToString() +
            "\na5: " + a5.ToString() +
            "\na6: " + a6.ToString() +
            "\na7: " + a7.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
