//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class JointPositionMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/JointPosition";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public JointQuantityMsg position;

        public JointPositionMsg()
        {
            this.header = new HeaderMsg();
            this.position = new JointQuantityMsg();
        }

        public JointPositionMsg(HeaderMsg header, JointQuantityMsg position)
        {
            this.header = header;
            this.position = position;
        }

        public static JointPositionMsg Deserialize(MessageDeserializer deserializer) => new JointPositionMsg(deserializer);

        private JointPositionMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.position = JointQuantityMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "JointPositionMsg: " +
            "\nheader: " + header.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
