//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class JointVelocityMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/JointVelocity";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public JointQuantityMsg velocity;

        public JointVelocityMsg()
        {
            this.header = new HeaderMsg();
            this.velocity = new JointQuantityMsg();
        }

        public JointVelocityMsg(HeaderMsg header, JointQuantityMsg velocity)
        {
            this.header = header;
            this.velocity = velocity;
        }

        public static JointVelocityMsg Deserialize(MessageDeserializer deserializer) => new JointVelocityMsg(deserializer);

        private JointVelocityMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.velocity = JointQuantityMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.velocity);
        }

        public override string ToString()
        {
            return "JointVelocityMsg: " +
            "\nheader: " + header.ToString() +
            "\nvelocity: " + velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
