//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class JointDampingMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/JointDamping";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public JointQuantityMsg damping;

        public JointDampingMsg()
        {
            this.header = new HeaderMsg();
            this.damping = new JointQuantityMsg();
        }

        public JointDampingMsg(HeaderMsg header, JointQuantityMsg damping)
        {
            this.header = header;
            this.damping = damping;
        }

        public static JointDampingMsg Deserialize(MessageDeserializer deserializer) => new JointDampingMsg(deserializer);

        private JointDampingMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.damping = JointQuantityMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.damping);
        }

        public override string ToString()
        {
            return "JointDampingMsg: " +
            "\nheader: " + header.ToString() +
            "\ndamping: " + damping.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
