//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class JointImpedanceControlModeMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/JointImpedanceControlMode";
        public override string RosMessageName => k_RosMessageName;

        //  Stiffness values in [Nm/rad]. Stiffness values must be >= 0. 
        public JointQuantityMsg joint_stiffness;
        //  Damping values. Damping values must be between 0 and 1. 
        public JointQuantityMsg joint_damping;

        public JointImpedanceControlModeMsg()
        {
            this.joint_stiffness = new JointQuantityMsg();
            this.joint_damping = new JointQuantityMsg();
        }

        public JointImpedanceControlModeMsg(JointQuantityMsg joint_stiffness, JointQuantityMsg joint_damping)
        {
            this.joint_stiffness = joint_stiffness;
            this.joint_damping = joint_damping;
        }

        public static JointImpedanceControlModeMsg Deserialize(MessageDeserializer deserializer) => new JointImpedanceControlModeMsg(deserializer);

        private JointImpedanceControlModeMsg(MessageDeserializer deserializer)
        {
            this.joint_stiffness = JointQuantityMsg.Deserialize(deserializer);
            this.joint_damping = JointQuantityMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_stiffness);
            serializer.Write(this.joint_damping);
        }

        public override string ToString()
        {
            return "JointImpedanceControlModeMsg: " +
            "\njoint_stiffness: " + joint_stiffness.ToString() +
            "\njoint_damping: " + joint_damping.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
