//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class SinePatternControlModeMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/SinePatternControlMode";
        public override string RosMessageName => k_RosMessageName;

        //  The degree of freedom for performing the sine oscillation.
        public int cartesian_dof;
        //  The value of the frequency for the sine oscillation [Hz].
        public double frequency;
        //  The value of the amplitude. In [N].
        public double amplitude;
        //  The value of the stiffness. In [N/m].
        public double stiffness;

        public SinePatternControlModeMsg()
        {
            this.cartesian_dof = 0;
            this.frequency = 0.0;
            this.amplitude = 0.0;
            this.stiffness = 0.0;
        }

        public SinePatternControlModeMsg(int cartesian_dof, double frequency, double amplitude, double stiffness)
        {
            this.cartesian_dof = cartesian_dof;
            this.frequency = frequency;
            this.amplitude = amplitude;
            this.stiffness = stiffness;
        }

        public static SinePatternControlModeMsg Deserialize(MessageDeserializer deserializer) => new SinePatternControlModeMsg(deserializer);

        private SinePatternControlModeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cartesian_dof);
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.amplitude);
            deserializer.Read(out this.stiffness);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cartesian_dof);
            serializer.Write(this.frequency);
            serializer.Write(this.amplitude);
            serializer.Write(this.stiffness);
        }

        public override string ToString()
        {
            return "SinePatternControlModeMsg: " +
            "\ncartesian_dof: " + cartesian_dof.ToString() +
            "\nfrequency: " + frequency.ToString() +
            "\namplitude: " + amplitude.ToString() +
            "\nstiffness: " + stiffness.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
