//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class SplineSegmentMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/SplineSegment";
        public override string RosMessageName => k_RosMessageName;

        //  This message describes a segment of a spline path
        public const int SPL = 0;
        public const int LIN = 1;
        public const int CIRC = 2;
        //  The type of the spline segment
        public int type;
        //  The endpoint of the current segment
        public CartesianPoseMsg point;
        //  Auxiliary point. Only used for circular segments
        public CartesianPoseMsg point_aux;

        public SplineSegmentMsg()
        {
            this.type = 0;
            this.point = new CartesianPoseMsg();
            this.point_aux = new CartesianPoseMsg();
        }

        public SplineSegmentMsg(int type, CartesianPoseMsg point, CartesianPoseMsg point_aux)
        {
            this.type = type;
            this.point = point;
            this.point_aux = point_aux;
        }

        public static SplineSegmentMsg Deserialize(MessageDeserializer deserializer) => new SplineSegmentMsg(deserializer);

        private SplineSegmentMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            this.point = CartesianPoseMsg.Deserialize(deserializer);
            this.point_aux = CartesianPoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.point);
            serializer.Write(this.point_aux);
        }

        public override string ToString()
        {
            return "SplineSegmentMsg: " +
            "\ntype: " + type.ToString() +
            "\npoint: " + point.ToString() +
            "\npoint_aux: " + point_aux.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
