//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class SplineMsg : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/Spline";
        public override string RosMessageName => k_RosMessageName;

        //  The describes a motion along a spline
        public SplineSegmentMsg[] segments;

        public SplineMsg()
        {
            this.segments = new SplineSegmentMsg[0];
        }

        public SplineMsg(SplineSegmentMsg[] segments)
        {
            this.segments = segments;
        }

        public static SplineMsg Deserialize(MessageDeserializer deserializer) => new SplineMsg(deserializer);

        private SplineMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.segments, SplineSegmentMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.segments);
            serializer.Write(this.segments);
        }

        public override string ToString()
        {
            return "SplineMsg: " +
            "\nsegments: " + System.String.Join(", ", segments.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
