//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class SetEndpointFrameRequest : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/SetEndpointFrame";
        public override string RosMessageName => k_RosMessageName;

        //  This service allows to select the frame that is used for cartesian positioning
        //  Id of Sunrise frame
        public string frame_id;

        public SetEndpointFrameRequest()
        {
            this.frame_id = "";
        }

        public SetEndpointFrameRequest(string frame_id)
        {
            this.frame_id = frame_id;
        }

        public static SetEndpointFrameRequest Deserialize(MessageDeserializer deserializer) => new SetEndpointFrameRequest(deserializer);

        private SetEndpointFrameRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
        }

        public override string ToString()
        {
            return "SetEndpointFrameRequest: " +
            "\nframe_id: " + frame_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
