//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class SetPTPJointSpeedLimitsRequest : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/SetPTPJointSpeedLimits";
        public override string RosMessageName => k_RosMessageName;

        //  This service allows to set relative joint velocity and acceleration of the robot.
        //  Set a parameter to -1 to ignore it
        //  Relative velocity of the individual joints, 0.0 < value <= 1
        public double joint_relative_velocity;
        //  Relative acceleration of the individual joints, 0.0 < value <= 1.0
        public double joint_relative_acceleration;

        public SetPTPJointSpeedLimitsRequest()
        {
            this.joint_relative_velocity = 0.0;
            this.joint_relative_acceleration = 0.0;
        }

        public SetPTPJointSpeedLimitsRequest(double joint_relative_velocity, double joint_relative_acceleration)
        {
            this.joint_relative_velocity = joint_relative_velocity;
            this.joint_relative_acceleration = joint_relative_acceleration;
        }

        public static SetPTPJointSpeedLimitsRequest Deserialize(MessageDeserializer deserializer) => new SetPTPJointSpeedLimitsRequest(deserializer);

        private SetPTPJointSpeedLimitsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_relative_velocity);
            deserializer.Read(out this.joint_relative_acceleration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_relative_velocity);
            serializer.Write(this.joint_relative_acceleration);
        }

        public override string ToString()
        {
            return "SetPTPJointSpeedLimitsRequest: " +
            "\njoint_relative_velocity: " + joint_relative_velocity.ToString() +
            "\njoint_relative_acceleration: " + joint_relative_acceleration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
