//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class SetSpeedOverrideRequest : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/SetSpeedOverride";
        public override string RosMessageName => k_RosMessageName;

        //  Override the velocity factor for all motions (relative between 0.0 and 1.0)
        public double override_reduction;

        public SetSpeedOverrideRequest()
        {
            this.override_reduction = 0.0;
        }

        public SetSpeedOverrideRequest(double override_reduction)
        {
            this.override_reduction = override_reduction;
        }

        public static SetSpeedOverrideRequest Deserialize(MessageDeserializer deserializer) => new SetSpeedOverrideRequest(deserializer);

        private SetSpeedOverrideRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.override_reduction);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.override_reduction);
        }

        public override string ToString()
        {
            return "SetSpeedOverrideRequest: " +
            "\noverride_reduction: " + override_reduction.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
