//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class SetWorkpieceRequest : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/SetWorkpiece";
        public override string RosMessageName => k_RosMessageName;

        //  This service allows to attach a workpiece to the robots tool.
        //  Setting a new workpiece automatically detaches the old one.
        //  Id of Sunrise workpiece template. Leave emtpy to detach current workpiece.
        public string workpiece_id;

        public SetWorkpieceRequest()
        {
            this.workpiece_id = "";
        }

        public SetWorkpieceRequest(string workpiece_id)
        {
            this.workpiece_id = workpiece_id;
        }

        public static SetWorkpieceRequest Deserialize(MessageDeserializer deserializer) => new SetWorkpieceRequest(deserializer);

        private SetWorkpieceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.workpiece_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.workpiece_id);
        }

        public override string ToString()
        {
            return "SetWorkpieceRequest: " +
            "\nworkpiece_id: " + workpiece_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
