//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class TimeToDestinationResponse : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/TimeToDestination";
        public override string RosMessageName => k_RosMessageName;

        public double remaining_time;

        public TimeToDestinationResponse()
        {
            this.remaining_time = 0.0;
        }

        public TimeToDestinationResponse(double remaining_time)
        {
            this.remaining_time = remaining_time;
        }

        public static TimeToDestinationResponse Deserialize(MessageDeserializer deserializer) => new TimeToDestinationResponse(deserializer);

        private TimeToDestinationResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.remaining_time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.remaining_time);
        }

        public override string ToString()
        {
            return "TimeToDestinationResponse: " +
            "\nremaining_time: " + remaining_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
