//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class MoveToCartesianPoseGoal : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/MoveToCartesianPose";
        public override string RosMessageName => k_RosMessageName;

        //  Goal
        public CartesianPoseMsg cartesian_pose;

        public MoveToCartesianPoseGoal()
        {
            this.cartesian_pose = new CartesianPoseMsg();
        }

        public MoveToCartesianPoseGoal(CartesianPoseMsg cartesian_pose)
        {
            this.cartesian_pose = cartesian_pose;
        }

        public static MoveToCartesianPoseGoal Deserialize(MessageDeserializer deserializer) => new MoveToCartesianPoseGoal(deserializer);

        private MoveToCartesianPoseGoal(MessageDeserializer deserializer)
        {
            this.cartesian_pose = CartesianPoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cartesian_pose);
        }

        public override string ToString()
        {
            return "MoveToCartesianPoseGoal: " +
            "\ncartesian_pose: " + cartesian_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
