//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class MoveAlongSplineGoal : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/MoveAlongSpline";
        public override string RosMessageName => k_RosMessageName;

        //  Goal
        public SplineMsg spline;

        public MoveAlongSplineGoal()
        {
            this.spline = new SplineMsg();
        }

        public MoveAlongSplineGoal(SplineMsg spline)
        {
            this.spline = spline;
        }

        public static MoveAlongSplineGoal Deserialize(MessageDeserializer deserializer) => new MoveAlongSplineGoal(deserializer);

        private MoveAlongSplineGoal(MessageDeserializer deserializer)
        {
            this.spline = SplineMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.spline);
        }

        public override string ToString()
        {
            return "MoveAlongSplineGoal: " +
            "\nspline: " + spline.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
