//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Iiwa
{
    [Serializable]
    public class MoveToJointPositionGoal : Message
    {
        public const string k_RosMessageName = "iiwa_msgs/MoveToJointPosition";
        public override string RosMessageName => k_RosMessageName;

        //  Goal
        public JointPositionMsg joint_position;

        public MoveToJointPositionGoal()
        {
            this.joint_position = new JointPositionMsg();
        }

        public MoveToJointPositionGoal(JointPositionMsg joint_position)
        {
            this.joint_position = joint_position;
        }

        public static MoveToJointPositionGoal Deserialize(MessageDeserializer deserializer) => new MoveToJointPositionGoal(deserializer);

        private MoveToJointPositionGoal(MessageDeserializer deserializer)
        {
            this.joint_position = JointPositionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_position);
        }

        public override string ToString()
        {
            return "MoveToJointPositionGoal: " +
            "\njoint_position: " + joint_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
